---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.17"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.18"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.19"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.20"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.21"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    target-branch: "release-0.17"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.17 tracks the 0.29 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.30.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.18"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.18 tracks the 0.30 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.31.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.19"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.19 tracks the 0.31 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.32.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.20"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.20 tracks the 0.32 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.33.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.21"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.21 tracks the 0.33 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.34.0-alpha.0"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    ignore:
      # These are included by k8s.io/client-go
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
  - package-ecosystem: gomod
    directory: "/tools"
    schedule:
      interval: weekly
    groups:
      tools:
        patterns:
          - "*"
