---
name: 'Post Mortem'
description: 'Autopsy'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Report available disk space"
        df -h
        echo "::endgroup::"
        echo "::group::Report available RAM"
        free -h
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Running post mortem"
        make post-mortem
        echo "::endgroup::"

    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
      with:
        name: submariner-gather
        path: gather_output
