---
name: Upgrade

on:
  pull_request:
    branches: [devel]

permissions: {}

jobs:
  upgrade-e2e:
    name: Latest Release to Latest Version
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install an old cluster, upgrade it and check it
        uses: ./gh-actions/upgrade-e2e

      - name: Post Mortem
        if: failure()
        uses: ./gh-actions/post-mortem
